# dev

logging:
  level:
    ROOT: WARN
    org.ontbrowser: DEBUG

spring:
  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/

# Actuator
management:
  endpoint:
    env:
      show-values: always
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
